<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Qsp_Mum_faculty2" ignored="0" name="Test1" tests="2" failures="1" timestamp="05 May 2018 14:21:59 GMT" time="16.02" errors="0">
  <testcase name="invalidLogin" time="1.313" classname="script.TestScript">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at script.TestScript.invalidLogin(TestScript.java:36)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- invalidLogin -->
  <testcase name="validLogin" time="3.259" classname="script.TestScript"/>
</testsuite> <!-- Test1 -->
